theme: jekyll-theme-hacker
title: octaedre
description: [Transform your Novation Launchpad in a circular sequencer. Stop making music with your eyes fixed on the screen. Ocataedre fells intuitive and tactile. It gives a different perspective on sequencing.]
